### ISSUE TITLE
API Phase 1: Data Retrieval MVP

### ISSUE THREAD

**Issue by regetz** [NCEAS/vegbank2#41]
#### Outcome

Working implementation of API functionality for retrieving "Plot with Observation" record(s) from the VegBank DB deployed to K8s.

#### Details

Phased approach:
1. Get a single plot observation using observation accession code (_see open questions below_)
2. Get all plot observations

Scope of information to include with each record:
- An illustrative and informative subset of fields (TBD) from the **plot** table, including `accessionCode`
  - Do _**not**_ return records with 4 < `confidentialityStatus`
  - Do _**not**_ return `confidentialityReason`, `realLatitude`, `realLongitude`
- Associated **place(s)** as a nested array of objects, with `placeName` and `accessionCode` from **namedPlace**
- An illustrative and informative subset of fields (TBD) from the **observation** table, including `accessionCode`
- Associated **disturbanceObs** as a nested array, with `disturbanceType`, `disturbanceIntensity`, and `disturbanceComment`
- Associated **soilTaxon** as a nested object, with `soilName`, `soilLevel`, and `accessionCode`
- Associated **soilObs** as a nested array, with `soilHorizon`, `soilTexture`, and `soilDescription`
- Associated **project** as a nested object, with `projectName` and `accessionCode`
  - Don't need to get associated **party** information for now (_deferring to later_)
- Associated **coverMethod** as a nested object, with `coverType` and `accessionCode`
  - Don't need to get associated **coverTypes** for now (_deferring to later_)
- Associated **stratumMethod** as a nested object, with `stratumMethodName` and `accessionCode`
  - Don't need to get associated **stratumTypes** for now (_deferring to later_)

#### Open questions
- VegBank maintains `accessionCode` for both plots and observations. Here if we are exposing _**plot observation**_ resources, then presumably we are working with _observation_ accession codes. And if we are flattening out the returned records in cases where a plot has multiple associated observations (i.e., both plot and observation fields will be top level fields in the JSON record, and plot information will be repeated across multiple associated observation records if they exist), then we will need to disambiguate `plot.accessionCode` from `observation.accessionCode`.
- Extending the previous bullet ... do we anticipate providing a separate set of endpoint for plots by themselves? Implementation is out of scope for this ticket regardless, but we need to discuss it because if the answer is yes, then we should probably make sure we implement the current ticket functionality via a `plot_observations` (or similarly named) endpoint rather than just `plots`, because we'll need to reserve the latter for interacting with pure *plot* resources.

#### Out of scope?
- Retrieving other associated resources beyond what's listed above; this includes taxon observations, taxon interpretations, community classifications, parties, references, etc.
- Handling embargo information
- Retrieving associated plot observation **graphic** information
- Retrieving associated **observationSynonym** information
- TBD - Authentication?
- TBD - Logging?
- TBD - Performance testing?
- TBD - Full testing
- TBD - Limiting/paging results when many records are returned

#### Acceptance criteria
- [x] Running service that accepts requests and returns data as specified above
- [x] Use of JSON as the serialization format all around
- [x] Functionality can be demonstrated using a basic client (e.g. curl or Postman)

**Comment by regetz** [comment]
Couple of thoughts as we further groom this.

First, I'm leaning toward sticking with JSON for both requests and responses, including returned data. I think it'll be a simpler starting point for this MVP, and maybe even what we do in the end. Some reasoning:
1. JSON support is so mature, easier to get moving faster
2. It will naturally accommodate nesting (like species observations within plot observations, and plot observations within plots)
3. Responses will be simpler bc service-related metadata (including pagination info) and veg data can all be in the same JSON response
4. It will be more human readable, especially with data sparseness
5. ... and similarly we can validate the data much more easily than if we used something like CSV
6. It'll be simpler to add fields, during dev/testing time if not later too

Even looking ahead beyond the MVPs, I could imagine keeping JSON everywhere, but selectively adding a few designated "bulk" API actions that support another format for upload and/or export as an option.

Second, after thinking a bit more, I'm comfortable with punting on auth for the data retrieval MVP work, and potentially even for upcoming data upload MVP work as long as we're only deploying to our internal dev environment.

**Comment by RWShelton** [comment]
This comment is copied on the child ticket for the API pod as it's relevant for both: 

The API is now networked to the DB pod. I've created two endpoints, one that gets a plot via an accession code, and one that gets all plots in the database. I've also included a document about how to set up port forwarding for local testing. It's in a separate file right now, but I'm planning to move it into one condensed document tomorrow. Next steps for the API are creating the joins that will connect the plot data up to observations and the rest of the necessary tables to get a complete view of the data.

**Comment by regetz** [comment]
Complete a long time ago. This issue was initially scoped at accepting requests for a set of (multiple) observations via either a list of accession codes or a search query, but that work has been deferred to the future.
